In [3]:
import pandas as pd
df=pd.read_csv("Advertising.csv")
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [5]:
df.isna().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [6]:
df.shape

(200, 5)

In [8]:
x=df[["TV","Radio","Newspaper"]]
y=df["Sales"]

In [10]:
print(x.shape)
print(y.shape)

(200, 3)
(200,)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1) 
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(160, 3)
(40, 3)
(160,)
(40,)

In [12]:
x.columns

Index(['TV', 'Radio', 'Newspaper'], dtype='object')

In [14]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print(y_pred)

[21.73577184 16.45693776  7.65993185 17.89202679 18.67730671 23.86271904
 16.33623628 13.45649226  9.177296   17.36056228 14.4677995   9.85697601
 17.26057027 16.71866935 15.09530285 15.58923732 12.45188167 17.27925151
 11.0944114  18.06889853  9.33433055 12.91345761  8.7842804  10.46670654
 11.40303174 15.03104665  9.78479388 19.46028647 18.22954934 17.1958903
 21.60304218 14.71901407 16.29205532 12.36432281 19.98831261 15.37556411
 13.96678297 10.06809496 20.97197274  7.45877832]

In [15]:
diff=pd.DataFrame({"Actual":y_test,"Predicted":y_pred})
diff

     Actual  Predicted
58     23.8  21.735772
40     16.6  16.456938
34      9.5   7.659932
102    14.8  17.892027
184    17.6  18.677307
198    25.5  23.862719
95     16.9  16.336236
4      12.9  13.456492
29     10.5   9.177296
168    17.1  17.360562
171    14.5  14.467799
18     11.3   9.856976
11     17.4  17.260570
89     16.7  16.718669
110    13.4  15.095303
118    15.9  15.589237
159    12.9  12.451882
35     12.8  17.279252
136     9.5  11.094411
59     18.4  18.068899
51     10.7   9.334331
16     12.5  12.913458
44      8.5   8.784280
94     11.5  10.466707
31     11.9  11.403032
162    14.9  15.031047
38     10.1   9.784794
28     18.9  19.460286
193    19.6  18.229549
27     15.9  17.195890
47     23.2  21.603042
165    11.9  14.719014
194    17.3  16.292055
177    11.7  12.364323
176    20.2  19.988313
97     15.5  15.375564
174    11.5  13.966783
73     11.0  10.068095
69     22.3  20.971973
172     7.6   7.458778

In [16]:
print("Coefficient: ",lr.coef_)
print("Intercept",lr.intercept_)

Coefficient:  [0.0468431  0.17854434 0.00258619]
Intercept 2.9079470208164295

In [17]:
from sklearn import metrics
print("MAE: ",metrics.mean_absolute_error(y_test,y_pred))
print("MSE: ",metrics.mean_squared_error(y_test,y_pred))
print("R2 Score : ",metrics.r2_score(y_test,y_pred))

MAE:  1.0402154012924718
MSE:  1.9918855518287906
R2 Score :  0.8927605914615384

In [18]:
df=pd.read_csv("FuelConsumptionCo2.csv")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   MODELYEAR                 1067 non-null   int64
 1   MAKE                      1067 non-null   object
 2   MODEL                     1067 non-null   object
 3   VEHICLECLASS              1067 non-null   object
 4   ENGINESIZE                1067 non-null   float64
 5   CYLINDERS                 1067 non-null   int64
 6   TRANSMISSION              1067 non-null   object
 7   FUELTYPE                  1067 non-null   object
 8   FUELCONSUMPTION_CITY      1067 non-null   float64
 9   FUELCONSUMPTION_HWY       1067 non-null   float64
 10  FUELCONSUMPTION_COMB      1067 non-null   float64
 11  FUELCONSUMPTION_COMB_MPG  1067 non-null   int64
 12  CO2EMISSIONS              1067 non-null   int64
dtypes: float64(4), int64(4), object(5)
memory usage: 108.5+ KB

In [21]:
df.drop(columns=['MAKE',"MODEL","VEHICLECLASS","TRANSMISSION","FUELTYPE"],axis=1,inplace=True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   MODELYEAR                 1067 non-null   int64
 1   ENGINESIZE                1067 non-null   float64
 2   CYLINDERS                 1067 non-null   int64
 3   FUELCONSUMPTION_CITY      1067 non-null   float64
 4   FUELCONSUMPTION_HWY       1067 non-null   float64
 5   FUELCONSUMPTION_COMB      1067 non-null   float64
 6   FUELCONSUMPTION_COMB_MPG  1067 non-null   int64
 7   CO2EMISSIONS              1067 non-null   int64
dtypes: float64(4), int64(4)
memory usage: 66.8 KB

In [24]:
df['Age']=2026-df["MODELYEAR"]
df

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,Age
0,2014,2.0,4,9.9,6.7,8.5,33,196,12
1,2014,2.4,4,11.2,7.7,9.6,29,221,12
2,2014,1.5,4,6.0,5.8,5.9,48,136,12
3,2014,3.5,6,12.7,9.1,11.1,25,255,12
4,2014,3.5,6,12.1,8.7,10.6,27,244,12
...,...,...,...,...,...,...,...,...,...
1062,2014,3.0,6,13.4,9.8,11.8,24,271,12
1063,2014,3.2,6,13.2,9.5,11.5,25,264,12
1064,2014,3.0,6,13.4,9.8,11.8,24,271,12
1065,2014,3.2,6,12.9,9.3,11.3,25,260,12
1066,2014,3.2,6,14.9,10.2,12.8,22,294,12

In [25]:
df.corr(numeric_only=True)

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,Age
MODELYEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENGINESIZE,NaN,1.000000,0.934011,0.832225,0.778746,0.819482,-0.808554,0.874154,NaN
CYLINDERS,NaN,0.934011,1.000000,0.796473,0.724594,0.776788,-0.770430,0.849685,NaN
FUELCONSUMPTION_CITY,NaN,0.832225,0.796473,1.000000,0.965718,0.995542,-0.935613,0.898039,NaN
FUELCONSUMPTION_HWY,NaN,0.778746,0.724594,0.965718,1.000000,0.985804,-0.893809,0.861748,NaN
FUELCONSUMPTION_COMB,NaN,0.819482,0.776788,0.995542,0.985804,1.000000,-0.927965,0.892129,NaN
FUELCONSUMPTION_COMB_MPG,NaN,-0.808554,-0.770430,-0.935613,-0.893809,-0.927965,1.000000,-0.906394,NaN
CO2EMISSIONS,NaN,0.874154,0.849685,0.898039,0.861748,0.892129,-0.906394,1.000000,NaN
Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
x=df[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_COMB']]
y=df['CO2EMISSIONS']

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1) 
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(853, 3)
(214, 3)
(853,)
(214,)

In [29]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print(y_pred)

[257.0729753  193.62675365 198.61947156 184.0315625  308.84886971
 222.06199356 185.00408977 193.38929893 234.70484808 197.40948958
 217.83256226 260.96308439 200.32707139 363.64971908 200.51083953
 192.73062136 193.99428993 314.31649706 261.88192508 215.88750772
 440.76775066 216.07127586 254.46924319 258.96434327 279.75495223
 239.56748443 162.03372438 288.13465573 187.18659903 231.68539877
 229.84221172 367.53982816 246.32148875 360.70666476 285.37813365
 315.9704103  351.66277803 181.16766727 341.17972436 257.62427972
 239.56748443 373.66062742 215.15243517 257.20305686 256.41429773
 201.53705338 189.73664457 161.53335371 181.11398069 250.02782969
 189.13165357 336.15602827 329.4839246  344.85508713 211.26232608
 269.05715225 208.29105769 289.16086958 263.22198863 185.24154449
 209.07981683 238.80693936 209.31727154 194.72936248 215.15243517
 193.38929893 259.33187954 253.31294778 204.45463519 209.55472626
 211.26232608 211.26232608 302.91183859 245.34896148 354.32019672
 316.65179628 177.22387161 308.87157811 204.45463519 262.24946136
 336.10234169 184.87400821 310.87031923 325.14437859 211.26232608
 353.60783257 254.65301133 253.12917964 205.42716246 248.45031143
 342.22864661 294.86595164 185.00408977 249.23907056 211.26232608
 204.45463519 342.22864661 391.90119085 218.07001698 288.29571546
 211.99739864 335.12981442 216.12496244 264.79950689 203.71956263
 294.86595164 191.44424439 360.70666476 198.25193529 204.45463519
 219.7776168  362.360578   361.07420103 305.56375162 360.70666476
 254.10170691 209.26358496 216.07127586 321.25426951 198.61947156
 255.6255386  278.91250652 203.48210792 262.24946136 191.81178067
 208.34474427 318.6505374  330.32086465 324.59307418 201.53705338
 211.99739864 187.18659903 263.03822049 321.38985673 390.85501015
 322.64801964 386.41359665 194.9668172  308.19019214 224.64025316
 185.84653548 209.31727154 205.42716246 173.80867196 286.66451062
 205.42716246 369.88063305 350.19263292 315.9704103  264.98327503
 203.48210792 254.15539349 368.06291851 345.69753284 232.70610696
 205.37347588 283.27752504 329.2946508  193.38929893 197.64694429
 179.40638087 247.47778416 278.3612021  181.9564264  261.93561166
 316.70548286 228.76781696 255.07423418 313.78790104 235.62368877
 324.49120668 292.49967424 292.18582454 189.13165357 323.19932405
 258.04550257 387.64628704 252.9454115  167.55228548 440.76775066
 302.88362452 360.70666476 251.23781168 191.68169911 302.72807045
 248.26654329 228.53036224 244.37643421 309.53576135 183.90148094
 207.372217   185.24154449 206.16223501 377.97195936 294.86595164
 268.87338411 253.12917964 250.02782969 323.51317375 294.86595164
 244.37643421 258.54312041 257.01928873 305.8294204  262.06569322
 212.23485335 189.13165357 253.68048406 219.7776168  275.68107501
 189.13165357 266.32333858 262.24946136 169.44365344]

In [30]:
diff=pd.DataFrame({"Actual":y_test,"Predicted":y_pred})
diff

     Actual   Predicted
133     274  257.072975
340     200  193.626754
948     196  198.619472
704     161  184.031563
661     320  308.848870
..      ...         ...
961     301  275.681075
523     184  189.131654
884     274  266.323339
8       267  262.249461
415     126  169.443653

[214 rows x 2 columns]

In [31]:
print("Coefficient: ",lr.coef_)
print("Intercept",lr.intercept_)

Coefficient:  [11.56295409  6.91231122  9.72527271]
Intercept 65.17950048137254

In [32]:
from sklearn import metrics
print("MAE: ",metrics.mean_absolute_error(y_test,y_pred))
print("MSE: ",metrics.mean_squared_error(y_test,y_pred))
print("R2 Score : ",metrics.r2_score(y_test,y_pred))

MAE:  16.64682799882323
MSE:  546.2591396903438
R2 Score :  0.8653355812644816

In [33]:
#coffecient of determination=r2 score

In [34]:
df=pd.read_csv("polylinearregression.csv")
df

   sno  Temperature  Pressure
0    1            0    0.0002
1    2           20    0.0012
2    3           40    0.0060
3    4           60    0.0300
4    5           80    0.0900
5    6          100    0.2700

In [36]:
x=df[["Temperature"]]
y=df["Pressure"]

In [37]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x,y)
y_pred=lr.predict(x)
print(y)

0    0.0002
1    0.0012
2    0.0060
3    0.0300
4    0.0900
5    0.2700
Name: Pressure, dtype: float64

In [38]:
from sklearn.metrics import r2_score
print("R2 Score",r2_score(y,y_pred))

R2 Score 0.690349972603981